language: node_js
node_js:
  - "10"
jobs:
  include:
    - stage: test
      script: yarn tpl test
    - script: yarn tpl lint
    - script: yarn tpl sls package
    - script: yarn tpl sls invoke local -f main -d '{"source":{"service":"local"}}'
stages:
  - test
notifications:
  email: false
  slack: bjacobel:xasDl3nTxo2feJGba70E43oR
